baseURL = "https://main--splendorous-cucurucho-139a42.netlify.app/"
languageCode = "en-us"
title = "Blog Dylan"
theme = "PaperMod"

  

[params.cover]
  linkFullImages = true

[params]
  ShowBreadCrumbs = true
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  author = "Observe"

[params.homeInfoParams]
  title = "UNIVERSES"
  content = "Explore the mysteries of multiverse theory, dark matter, and cosmic phenomena."


[menu]
  [[menu.main]]
    identifier = "Categories"
    name = "Categories"
    url = "categories"
    weight = 10

  [[menu.main]]
    identifier = "Tags"
    name = "Tags"
    url = "tags"
    weight = 20

  [[menu.main]]
    identifier = "Archives"
    name = "Archives"
    url = "archives"
    weight = 30